### ISSUE TITLE
HTML Tasarımı

### ISSUE THREAD

**Issue by oguzhantasci** [paufsc/journey-to-html#23]

**Comment by oguzhantasci** [comment]
@mehmetdik bana bu konu hakkında daha fazla bilgi verebilir misin ?

**Comment by mehmetdik** [comment]
@oguzhantasci tam olarak hatırlayamadım ama dizayn demek istemişim galiba

**Comment by oguzhantasci** [comment]
Tamamdır tasarım olarak düzeltiyorum

**Comment by kemalkanok** [comment]
canlarım en çok kullanılan tasarım modeli divlerdir lütfen güncelleyin :)

**Comment by ogta** [comment]
div is here :  https://github.com/paufsc/journey-to-html/blob/master/docs/tr/bloklar.md

**Comment by kemalkanok** [comment]
3985b94
`En çok kullanılan tasarım yöntemi tablolardır.`
bu ibare çok yanlış 2007lerden beri kullanılmıyor div is rules :)

**Comment by ogta** [comment]
kullanılan kaynakta böyle geçmekte bizim için div konusunu yazabilir misin ayrıntılı şekilde @kemalkanok

**Comment by necatikartal** [comment]
open issue - close issue - open issue - close .. :+1: :smile:

**Comment by kemalkanok** [comment]
kaynak url please :D

**Comment by kemalkanok** [comment]
@necatikartal  don't trol :rage:  :laughing:

**Comment by ogta** [comment]
Attigim linkin altinda yararlanilan kaynaklar mevcut linke bakarsan
gorursun :)

31 Ocak 2015 Cumartesi tarihinde, Kemal Kanok notifications@github.com
yazdı:

**Comment by kemalkanok** [comment]
tamamdir inceleyip doniyim sana
